linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - elseif

linters:
  enable:
    - gofmt
    - gocritic
    - unconvert
    - govet
    - golint
run:
  skip-dirs:
    - kbchat/types/
