version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofumpt

linters:
  enable:
    # Core recommended linters
    - errcheck # Checks for unchecked errors
    - govet # Go vet checks
    - ineffassign # Detects ineffectual assignments
    - staticcheck # Advanced static analysis
    - unused # Finds unused code

    # Code quality
    - misspell # Finds commonly misspelled words
    - unconvert # Unnecessary type conversions (already enabled in original)
    - unparam # Finds unused function parameters
    - gocritic # Various checks (already enabled in original)
    - revive # Fast, configurable linter (already enabled in original)

    # Security and best practices
    - gosec # Security-focused linter
    - bodyclose # Checks HTTP response body closed
    - noctx # Finds HTTP requests without context

  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - elseif

    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment

    revive:
      enable-all-rules: false

  exclusions:
    rules:
      # Exclude specific revive rules
      - linters:
          - revive
        text: "package-comments"

      - linters:
          - revive
        text: "exported"

      # Exclude specific staticcheck rules
      - linters:
          - staticcheck
        text: "ST1005"

      # Exclude specific gocritic rules
      - linters:
          - gocritic
        text: "ifElseChain"

      # Exclude all linters from generated types directory
      - path: "kbchat/types/"
        linters:
          - gocritic
          - gofumpt
          - revive
          - gosec
          - staticcheck
          - errcheck
          - govet
          - ineffassign
          - unused
          - misspell
          - unconvert
          - unparam
          - bodyclose
          - noctx

      # Exclude unparam from test files - test helpers designed for flexibility
      - path: "_test\\.go"
        linters:
          - unparam
