# Rename this file to `test_config.yaml`

config:
  bots:
    alice1:
      username: "alice"
      paperkey: "foo bar car..."
    bob1:
      username: "bob"
      paperkey: "one two three four..."
  teams:
    acme:
      # A real team that you add your alice1 and bob1 into
      name: "acme"
      # The channel to use
      topicname: "mysupercoolchannel"
