# Rename this file to `test_config.yaml`

config:
  bots:
    alice1:
      # Alice should have an active Stellar account with a little bit of XLM in it
      username: "alice"
      paperkey: "foo bar car..."
    }
    alice2:
      username: "alice"                # should be the same username as alice1 but...
      paperkey: "yo there paperkey..." # ...this should be a DIFFERENT paperkey than the one for alice1
    bob1:
      # Bob should have an active Stellar account with a little bit of XLM in it
      username: "bob"
      paperkey: "one two three four..."
    charlie1:
      # Charlie should be an account that does not have access to Stellar features
      username: "charlie"
      paperkey: "get this bread..."
